[
  { title: 'Curriculum Python', modules: ['Lecture Video'] },
  { title: 'M 1 : Python Basics Unit 01 - 06', modules: ['Lecture Video'] },
  { title: 'M 1 : Python Foundation Unit 07- 11', modules: ['Lecture Video'] },
  { title: 'M 1 : Python Advanced Unit 12 - 14', modules: ['Lecture Video'] },
  { title: 'MODULE 2 : Python Libraries Level 1', modules: ['Lecture Video'] },
  { title: 'MODULE 2 : Python Libraries Level 2', modules: ['Lecture Video'] },
  { title: 'MODULE 2 : Python Libraries Level 3', modules: ['Lecture Video'] },
  { title: 'MODULE 2 : Python Libraries Level 4', modules: ['Lecture Video'] },
  { title: 'MODULE 2 : Python Libraries Level 5', modules: ['Lecture Video'] },
  { title: 'M-2 : Project- Covid-19 Impact Analysis', modules: ['Lecture Video'] },
  { title: 'M-2 : Project- Google Image Scrapping', modules: ['Lecture Video'] },
  { title: 'M-2 : Project- WhatsApp Chat Analysis', modules: ['Lecture Video'] },
  { title: 'M-2 : Project- Movie Recommendation', modules: ['Lecture Video'] },
  { title: 'M-2 : Project- Price Comparison', modules: ['Lecture Video'] },
  { title: 'Module 3 : Statistics Unit 01 - 03', modules: ['Lecture Video'] },
  { title: 'Module 3 : Statistics Unit 04 - 06', modules: ['Lecture Video'] },
  { title: 'Module 3 Statistics Unit 07 - 09', modules: ['Lecture Video'] },
  { title: 'Module 4 : Feature Engineering', modules: ['Lecture Video'] },
  { title: 'Modue 5 : Exploratory Data Analysis : Unit 01', modules: ['Lecture Video'] },
  { title: 'Modue 5 : Exploratory Data Analysis : Unit 02', modules: ['Lecture Video'] },
  { title: 'Modue 6 : Machine Learning Part 1 : Regression', modules: ['Lecture Video'] },
  { title: 'Machine Learning Part 1 : Project', modules: ['Lecture Video'] },
  { title: 'Modue 6 : Machine Learning Part 2 : Logistic Regression', modules: ['Lecture Video'] },
  { title: 'Machine Learning Part 2 : Project', modules: ['Lecture Video'] },
  { title: 'Machine Learning Part 3 : Decision Tree', modules: ['Lecture Video'] },
  { title: 'Machine Learning Part 4 : Support Vector Machines', modules: ['Lecture Video'] },
  { title: 'Machine Learning Part 5 : Naive Bayes', modules: ['Lecture Video'] },
  { title: 'Machine Learning Part 5 : Project', modules: ['Lecture Video'] },
  { title: 'Machine Learning Part 6 : ET & its Types', modules: ['Lecture Video'] },
  { title: 'Machine Learning Part 7 : Boosting', modules: ['Lecture Video'] },
  { title: 'Machine Learning Part 8 : KNN Algorithm', modules: ['Lecture Video'] },
  { title: 'Machine Learning II : PCA', modules: ['Lecture Video'] },
  { title: 'Machine Learning II : Clustering Algorithms', modules: ['Lecture Video'] },
  { title: 'Machine Learning II : Anomaly Detection', modules: ['Lecture Video'] },
  { title: 'Machine Learning II : Time Series', modules: ['Lecture Video'] },
  { title: 'Deep Learning : Lecture 1 to 10', modules: ['Lecture Video'] },
  { title: 'Deep Learning : Lecture 11 to 17', modules: ['Lecture Video'] },
  { title: 'Module 9 - NLP', modules: ['Lecture Video'] },
  { title: 'NLP : Part 2', modules: ['Lecture Video'] },
  { title: 'NLP : Projects', modules: ['Lecture Video'] },
  { title: 'Computer Vision', modules: ['Lecture Video'] },
  { title: 'Computer Vision : Project 1', modules: ['Lecture Video'] },
  { title: 'Computer Vision : Project 2', modules: ['Lecture Video'] },
  { title: 'Computer Vision : Project 3', modules: ['Lecture Video'] },
  { title: 'Module 12 AGENTIC AI', modules: ['Lecture Video'] },
  { title: 'Module 12 : AGENTIC AI Project', modules: ['Lecture Video'] },
  { title: 'Module- GENERATIVE AI', modules: ['Lecture Video'] },
  { title: 'MODULE 11 : SQL | Notes & Study Material', modules: ['Lecture Video'] },
  { title: 'SQL : Unit 01 - 04', modules: ['Lecture Video'] },
  { title: 'SQL : Unit 05 - 08', modules: ['Lecture Video'] },
  { title: 'SQL : Unit 09 - 14', modules: ['Lecture Video'] },
  { title: 'SQL : Unit 15 - 18', modules: ['Lecture Video'] },
  { title: 'SQL : Unit 19', modules: ['Lecture Video'] },
  { title: 'SQL : Unit 20', modules: ['Lecture Video'] },
  { title: 'SQL Project - Music Store Data', modules: ['Lecture Video'] },
  { title: 'UPDATED POWER BI LECTURES', modules: ['Lecture Video'] },
  { title: 'MODULE 12 : Power BI | Notes & Study Material', modules: ['Lecture Video'] },
  { title: 'Power BI : Unit 01 - 07', modules: ['Lecture Video'] },
  { title: 'Power BI : Unit 08 - 12', modules: ['Lecture Video'] },
  { title: 'Power BI : Project 1', modules: ['Lecture Video'] },
  { title: 'Project - Real Estate', modules: ['Lecture Video'] },
  { title: 'Power BI : Project 2', modules: ['Lecture Video'] },
  { title: 'DAX FUNCTIONS & POWER QUERY', modules: ['Lecture Video'] },
  { title: 'MODULE 13 : Advance Excel | Notes & Study Material', modules: ['Lecture Video'] },
  { title: 'Basic Excel', modules: ['Lecture Video'] },
  { title: 'Intermediate Excel', modules: ['Lecture Video'] },
  { title: 'Moderate Excel', modules: ['Lecture Video'] },
  { title: 'Advance Excel', modules: ['Lecture Video'] },
  { title: 'Project- Analysis the Online Store Annual Report', modules: ['Lecture Video'] },
  { title: 'MODULE 14 : Tableau | Notes & Study Material', modules: ['Lecture Video'] },
  { title: 'Tableau : Unit 01', modules: ['Lecture Video'] },
  { title: 'Tableau : Unit 02', modules: ['Lecture Video'] },
  { title: 'Tableau : Unit 03', modules: ['Lecture Video'] },
  { title: 'Tableau : Unit 04', modules: ['Lecture Video'] },
  { title: 'Tableau Capstone Project - 01', modules: ['Lecture Video'] },
  { title: 'Tableau Capstone Project - 02 & 03', modules: ['Lecture Video'] },
  { title: 'SPECIAL VIRTUAL CLASS', modules: ['Lecture Video'] },
  { title: '20+ AI Tools Lectures', modules: ['Lecture Video'] }
]
